export const LOCAL_SEED = {
  "version": "1.8.8",
  "databaseVersion": "1.8.8",
  "categories": [
    {
      "CategoryID": "CAT_BREAKFAST",
      "CategoryName": "Breakfast",
      "Sort": 1,
      "Active": true,
      "ButtonColour": "#4F7D43",
      "UpdatedAt": ""
    },
    {
      "CategoryID": "CAT_COLD_SANDWICHES",
      "CategoryName": "Cold Sandwiches",
      "Sort": 2,
      "Active": true,
      "ButtonColour": "#E8EDDF",
      "UpdatedAt": ""
    },
    {
      "CategoryID": "CAT_TOASTED_SANDWICHES",
      "CategoryName": "Toasted Sandwiches",
      "Sort": 3,
      "Active": true,
      "ButtonColour": "#E8EDDF",
      "UpdatedAt": ""
    },
    {
      "CategoryID": "CAT_PANINIS",
      "CategoryName": "Paninis",
      "Sort": 4,
      "Active": true,
      "ButtonColour": "#E8EDDF",
      "UpdatedAt": ""
    },
    {
      "CategoryID": "CAT_DRINKS",
      "CategoryName": "Drinks",
      "Sort": 5,
      "Active": true,
      "ButtonColour": "#E8EDDF",
      "UpdatedAt": ""
    },
    {
      "CategoryID": "CAT_CAKES",
      "CategoryName": "Cakes",
      "Sort": 6,
      "Active": true,
      "ButtonColour": "#E8EDDF",
      "UpdatedAt": ""
    },
    {
      "CategoryID": "CAT_EXTRAS",
      "CategoryName": "Extras",
      "Sort": 7,
      "Active": true,
      "ButtonColour": "#E8EDDF",
      "UpdatedAt": ""
    },
    {
      "CategoryID": "CAT_HOT_DRINKS",
      "CategoryName": "Hot drinks",
      "Sort": 8,
      "Active": true,
      "ButtonColour": "#E8EDDF",
      "UpdatedAt": ""
    },
    {
      "CategoryID": "CAT_COLD_DRINKS",
      "CategoryName": "Cold Drinks",
      "Sort": 9,
      "Active": true,
      "ButtonColour": "#E8EDDF",
      "UpdatedAt": ""
    },
    {
      "CategoryID": "CAT_SWEET_TREATS",
      "CategoryName": "Sweet treats",
      "Sort": 10,
      "Active": true,
      "ButtonColour": "#E8EDDF",
      "UpdatedAt": ""
    },
    {
      "CategoryID": "CAT_PIZZA",
      "CategoryName": "Pizza",
      "Sort": 11,
      "Active": false,
      "ButtonColour": "#E8EDDF",
      "UpdatedAt": ""
    }
  ],
  "menu": [
    {
      "ItemID": "I1782649431040",
      "CategoryID": "CAT_BREAKFAST",
      "CategoryName": "Breakfast",
      "ItemName": "The Nook Full English",
      "Description": "2 bacon 2 sausage 2 egg 2 hash bean mushrooms Black pudding and toast",
      "Price": 10.95,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 1,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782652780758",
      "CategoryID": "CAT_BREAKFAST",
      "CategoryName": "Breakfast",
      "ItemName": "Build your own breakfast Cob",
      "Description": "Bacon or sausage as standard, add egg mushrooms tomato additional 70p",
      "Price": 3.75,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 2,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782669643290",
      "CategoryID": "CAT_BREAKFAST",
      "CategoryName": "Breakfast",
      "ItemName": "Scrambled Eggs on Toast",
      "Description": "",
      "Price": 3.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 3,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782669672463",
      "CategoryID": "CAT_BREAKFAST",
      "CategoryName": "Breakfast",
      "ItemName": "Beans on Toast",
      "Description": "",
      "Price": 3.2,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 4,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782669740358",
      "CategoryID": "CAT_BREAKFAST",
      "CategoryName": "Breakfast",
      "ItemName": "The Smashed Bagel",
      "Description": "Toasted Bagel With Smashed Avocado & Poached Egg",
      "Price": 5.95,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 5,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782669802819",
      "CategoryID": "CAT_BREAKFAST",
      "CategoryName": "Breakfast",
      "ItemName": "The Smoked Bagel",
      "Description": "Toasted bagel with scrambled egg & Smoked salmon",
      "Price": 7.95,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 6,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782669845961",
      "CategoryID": "CAT_BREAKFAST",
      "CategoryName": "Breakfast",
      "ItemName": "Thick Toast with Preserves V",
      "Description": "V",
      "Price": 2.4,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 7,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782669890055",
      "CategoryID": "CAT_BREAKFAST",
      "CategoryName": "Breakfast",
      "ItemName": "Toasted Tea Cake V",
      "Description": "",
      "Price": 2.75,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 8,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782669980937",
      "CategoryID": "CAT_COLD_SANDWICHES",
      "CategoryName": "Cold Sandwiches",
      "ItemName": "Ham",
      "Description": "",
      "Price": 5.25,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 9,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782669994547",
      "CategoryID": "CAT_COLD_SANDWICHES",
      "CategoryName": "Cold Sandwiches",
      "ItemName": "Cheese",
      "Description": "",
      "Price": 5.25,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 10,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782670023537",
      "CategoryID": "CAT_COLD_SANDWICHES",
      "CategoryName": "Cold Sandwiches",
      "ItemName": "Tuna Mayo",
      "Description": "",
      "Price": 5.75,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 11,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782670130797",
      "CategoryID": "CAT_COLD_SANDWICHES",
      "CategoryName": "Cold Sandwiches",
      "ItemName": "Cheese and red onion chutney",
      "Description": "",
      "Price": 5.75,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 12,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782670193173",
      "CategoryID": "CAT_COLD_SANDWICHES",
      "CategoryName": "Cold Sandwiches",
      "ItemName": "Ham or Cheese salad",
      "Description": "",
      "Price": 5.75,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 13,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782670559779",
      "CategoryID": "CAT_TOASTED_SANDWICHES",
      "CategoryName": "Toasted Sandwiches",
      "ItemName": "Cheese & Ham",
      "Description": "",
      "Price": 6.75,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 14,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782670578738",
      "CategoryID": "CAT_TOASTED_SANDWICHES",
      "CategoryName": "Toasted Sandwiches",
      "ItemName": "Cheese and red onion chutney",
      "Description": "",
      "Price": 6.75,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 15,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782670601704",
      "CategoryID": "CAT_TOASTED_SANDWICHES",
      "CategoryName": "Toasted Sandwiches",
      "ItemName": "Tuna crunch and red onion",
      "Description": "",
      "Price": 6.75,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 16,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782671896092",
      "CategoryID": "CAT_PANINIS",
      "CategoryName": "Paninis",
      "ItemName": "Ham & Cheese",
      "Description": "",
      "Price": 6.95,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 17,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782671920796",
      "CategoryID": "CAT_PANINIS",
      "CategoryName": "Paninis",
      "ItemName": "Cheese and red onion chutney",
      "Description": "",
      "Price": 6.95,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 18,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782671939084",
      "CategoryID": "CAT_PANINIS",
      "CategoryName": "Paninis",
      "ItemName": "Tuna crunch and red onion",
      "Description": "",
      "Price": 6.95,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 19,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782671977972",
      "CategoryID": "CAT_PANINIS",
      "CategoryName": "Paninis",
      "ItemName": "Bacon, Brie & Cranberry",
      "Description": "",
      "Price": 8.95,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 20,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672072753",
      "CategoryID": "CAT_PANINIS",
      "CategoryName": "Paninis",
      "ItemName": "Bacon and stilton",
      "Description": "",
      "Price": 8.95,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 21,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672112616",
      "CategoryID": "CAT_HOT_DRINKS",
      "CategoryName": "Hot drinks",
      "ItemName": "Mug of Tea",
      "Description": "",
      "Price": 1.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 22,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672129350",
      "CategoryID": "CAT_HOT_DRINKS",
      "CategoryName": "Hot drinks",
      "ItemName": "Pot of tea",
      "Description": "",
      "Price": 2.0,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 23,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672145664",
      "CategoryID": "CAT_HOT_DRINKS",
      "CategoryName": "Hot drinks",
      "ItemName": "Instant Coffee",
      "Description": "",
      "Price": 1.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 24,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672163878",
      "CategoryID": "CAT_HOT_DRINKS",
      "CategoryName": "Hot drinks",
      "ItemName": "Assorted Fruit tea",
      "Description": "",
      "Price": 1.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 25,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672184391",
      "CategoryID": "CAT_HOT_DRINKS",
      "CategoryName": "Hot drinks",
      "ItemName": "Latte",
      "Description": "",
      "Price": 3.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 26,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672204530",
      "CategoryID": "CAT_HOT_DRINKS",
      "CategoryName": "Hot drinks",
      "ItemName": "cappucino",
      "Description": "",
      "Price": 3.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 27,
      "LoyaltyEligible": true,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672220829",
      "CategoryID": "CAT_HOT_DRINKS",
      "CategoryName": "Hot drinks",
      "ItemName": "Americano",
      "Description": "",
      "Price": 3.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 28,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672237467",
      "CategoryID": "CAT_HOT_DRINKS",
      "CategoryName": "Hot drinks",
      "ItemName": "Mocha",
      "Description": "",
      "Price": 3.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 27,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672252677",
      "CategoryID": "CAT_HOT_DRINKS",
      "CategoryName": "Hot drinks",
      "ItemName": "Flat White",
      "Description": "",
      "Price": 3.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 28,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672268111",
      "CategoryID": "CAT_HOT_DRINKS",
      "CategoryName": "Hot drinks",
      "ItemName": "Esspresso",
      "Description": "",
      "Price": 3.0,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 29,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672296450",
      "CategoryID": "CAT_HOT_DRINKS",
      "CategoryName": "Hot drinks",
      "ItemName": "Hot Chocolate",
      "Description": "",
      "Price": 3.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 32,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672320049",
      "CategoryID": "CAT_COLD_DRINKS",
      "CategoryName": "Cold Drinks",
      "ItemName": "Milkshakes",
      "Description": "",
      "Price": 4.0,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 33,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672345976",
      "CategoryID": "CAT_COLD_DRINKS",
      "CategoryName": "Cold Drinks",
      "ItemName": "Bottle of soft drink",
      "Description": "",
      "Price": 2.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 34,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672515745",
      "CategoryID": "CAT_COLD_DRINKS",
      "CategoryName": "Cold Drinks",
      "ItemName": "Special Cold drink (glass bottle)",
      "Description": "",
      "Price": 2.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 35,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672569009",
      "CategoryID": "CAT_COLD_DRINKS",
      "CategoryName": "Cold Drinks",
      "ItemName": "Bottle of Water",
      "Description": "",
      "Price": 1.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 36,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672591327",
      "CategoryID": "CAT_COLD_DRINKS",
      "CategoryName": "Cold Drinks",
      "ItemName": "Can of Pop",
      "Description": "",
      "Price": 1.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 37,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672663601",
      "CategoryID": "CAT_SWEET_TREATS",
      "CategoryName": "Sweet treats",
      "ItemName": "ShortBread slice",
      "Description": "",
      "Price": 3.0,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 38,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672688196",
      "CategoryID": "CAT_SWEET_TREATS",
      "CategoryName": "Sweet treats",
      "ItemName": "Cake Slice",
      "Description": "",
      "Price": 3.75,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 39,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672707104",
      "CategoryID": "CAT_EXTRAS",
      "CategoryName": "Extras",
      "ItemName": "Sausage",
      "Description": "",
      "Price": 1.0,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 40,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672720488",
      "CategoryID": "CAT_EXTRAS",
      "CategoryName": "Extras",
      "ItemName": "x Bacon Extra",
      "Description": "",
      "Price": 1.0,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 41,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672739812",
      "CategoryID": "CAT_EXTRAS",
      "CategoryName": "Extras",
      "ItemName": "x Egg Extra",
      "Description": "",
      "Price": 1.0,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 41,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782672762420",
      "CategoryID": "CAT_EXTRAS",
      "CategoryName": "Extras",
      "ItemName": "Mushrooms",
      "Description": "",
      "Price": 1.0,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 42,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1782678920773",
      "CategoryID": "CAT_COLD_DRINKS",
      "CategoryName": "Cold Drinks",
      "ItemName": "Shandy bass",
      "Description": "",
      "Price": 2.5,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "drink",
      "Sort": 46,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "Imqzsdjw3l8nwp",
      "CategoryID": "CAT_COLD_SANDWICHES",
      "CategoryName": "Cold Sandwiches",
      "ItemName": "The Daddy sandwich",
      "Description": "",
      "Price": 5.9,
      "TaxRate": 0,
      "Active": true,
      "ShowOnTill": true,
      "KitchenRoute": "food",
      "Sort": 46,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    },
    {
      "ItemID": "I1783015856354672",
      "CategoryID": "CAT_PIZZA",
      "CategoryName": "Pizza",
      "ItemName": "Category placeholder",
      "Description": "",
      "Price": 0.0,
      "TaxRate": 0,
      "Active": false,
      "ShowOnTill": false,
      "KitchenRoute": "food",
      "Sort": 9999,
      "LoyaltyEligible": false,
      "CostPrice": "",
      "Barcode": "",
      "DeletedAt": "",
      "UpdatedAt": ""
    }
  ],
  "modifiers": [
    {
      "ModifierID": "M001",
      "ModifierName": "Add cream & marshmallows",
      "Price": 0.5,
      "Active": true,
      "ItemID": "",
      "Sort": "",
      "UpdatedAt": ""
    },
    {
      "ModifierID": "M004",
      "ModifierName": "Extra Espresso Shot",
      "Price": 0.75,
      "Active": true,
      "ItemID": "",
      "Sort": "",
      "UpdatedAt": ""
    }
  ],
  "prompts": [
    {
      "PromptID": "P1782656025085_933",
      "TriggerItemID": "I1782649431040",
      "PromptTitle": "toast",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782656060858_727",
      "TriggerItemID": "I1782649431040",
      "PromptTitle": "Eggs",
      "PromptType": "single",
      "Required": false,
      "Sort": 2,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782656217930_829",
      "TriggerItemID": "I1782649431040",
      "PromptTitle": "Additional item",
      "PromptType": "multi",
      "Required": true,
      "Sort": 3,
      "Active": true,
      "AllowNotes": true,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782669309730_362",
      "TriggerItemID": "I1782652780758",
      "PromptTitle": "Choose bacon or sausage",
      "PromptType": "single",
      "Required": true,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782669364652_641",
      "TriggerItemID": "I1782652780758",
      "PromptTitle": "additional Cob item",
      "PromptType": "single",
      "Required": false,
      "Sort": 2,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782670248767_972",
      "TriggerItemID": "I1782670193173",
      "PromptTitle": "Ham OR Cheese",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782670291939_777",
      "TriggerItemID": "I1782670193173",
      "PromptTitle": "Add bacon?",
      "PromptType": "single",
      "Required": false,
      "Sort": 2,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782670649954_117",
      "TriggerItemID": "I1782669980937",
      "PromptTitle": "Bread choice",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782670720725_802",
      "TriggerItemID": "I1782669980937",
      "PromptTitle": "Bread type options",
      "PromptType": "single",
      "Required": false,
      "Sort": 2,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782670841986_326",
      "TriggerItemID": "I1782669994547",
      "PromptTitle": "Bread Choice",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782670896865_479",
      "TriggerItemID": "I1782669994547",
      "PromptTitle": "bread type options",
      "PromptType": "single",
      "Required": false,
      "Sort": 2,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782670988765_8",
      "TriggerItemID": "I1782670023537",
      "PromptTitle": "Bread Choice",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782671039163_411",
      "TriggerItemID": "I1782670023537",
      "PromptTitle": "Bread Type Options",
      "PromptType": "single",
      "Required": false,
      "Sort": 2,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782671103928_679",
      "TriggerItemID": "I1782670130797",
      "PromptTitle": "Bread Choice",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782671137622_875",
      "TriggerItemID": "I1782670130797",
      "PromptTitle": "Bread Type Options",
      "PromptType": "single",
      "Required": false,
      "Sort": 2,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782671214961_788",
      "TriggerItemID": "I1782670193173",
      "PromptTitle": "Bread Choice",
      "PromptType": "single",
      "Required": false,
      "Sort": 3,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782671273652_723",
      "TriggerItemID": "I1782670193173",
      "PromptTitle": "Bread type Options",
      "PromptType": "single",
      "Required": false,
      "Sort": 4,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782671547423_898",
      "TriggerItemID": "I1782670559779",
      "PromptTitle": "Bread type options",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": false,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782671625353_843",
      "TriggerItemID": "I1782670559779",
      "PromptTitle": "Bread Type Options",
      "PromptType": "single",
      "Required": false,
      "Sort": 2,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782671731427_496",
      "TriggerItemID": "I1782670578738",
      "PromptTitle": "Bread Type Options",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782671801202_159",
      "TriggerItemID": "I1782670601704",
      "PromptTitle": "Bread Type Options",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782672804167_232",
      "TriggerItemID": "I1782672739812",
      "PromptTitle": "Egg Type",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782673004962_498",
      "TriggerItemID": "I1782672184391",
      "PromptTitle": "Add syrup",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782673229331_122",
      "TriggerItemID": "I1782672204530",
      "PromptTitle": "Add Syrup",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782673368316_835",
      "TriggerItemID": "I1782672268111",
      "PromptTitle": "Double or Single",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782673424197_513",
      "TriggerItemID": "I1782672220829",
      "PromptTitle": "With Milk?",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782673521633_691",
      "TriggerItemID": "I1782672296450",
      "PromptTitle": "Cream and Marshmallows?",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782673706645_426",
      "TriggerItemID": "I1782672320049",
      "PromptTitle": "Flavour",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782673782787_326",
      "TriggerItemID": "I1782672320049",
      "PromptTitle": "Add Cream and Marshmallows?",
      "PromptType": "single",
      "Required": false,
      "Sort": 2,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782678982466_39",
      "TriggerItemID": "I1782678920773",
      "PromptTitle": "with a glass?",
      "PromptType": "single",
      "Required": true,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782732026962_42",
      "TriggerItemID": "I1782669643290",
      "PromptTitle": "Bread choice",
      "PromptType": "single",
      "Required": true,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782732082198_82",
      "TriggerItemID": "I1782669672463",
      "PromptTitle": "Bread choice",
      "PromptType": "single",
      "Required": true,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782732169490_761",
      "TriggerItemID": "I1782669845961",
      "PromptTitle": "Bread options",
      "PromptType": "single",
      "Required": true,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "Pmqzseelbp0zgy",
      "TriggerItemID": "Imqzsdjw3l8nwp",
      "PromptTitle": "Bread Type Options",
      "PromptType": "single",
      "Required": false,
      "Sort": 1,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782847529725723",
      "TriggerItemID": "Imqzsdjw3l8nwp",
      "PromptTitle": "Bread choice",
      "PromptType": "single",
      "Required": false,
      "Sort": 2,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782847529725908",
      "TriggerItemID": "Imqzsdjw3l8nwp",
      "PromptTitle": "Bread type options",
      "PromptType": "single",
      "Required": false,
      "Sort": 3,
      "Active": true,
      "AllowNotes": false,
      "UpdatedAt": ""
    },
    {
      "PromptID": "P1782934439024872",
      "TriggerItemID": "I1782649431040",
      "PromptTitle": "Notes",
      "PromptType": "single",
      "Required": true,
      "Sort": 4,
      "Active": false,
      "AllowNotes": false,
      "UpdatedAt": ""
    }
  ],
  "promptOptions": [
    {
      "OptionID": "O1782656033788_182",
      "PromptID": "P1782656025085_933",
      "OptionText": "White",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782656040200_729",
      "PromptID": "P1782656025085_933",
      "OptionText": "Granary",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782656087934_118",
      "PromptID": "P1782656060858_727",
      "OptionText": "Fried",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782656097542_809",
      "PromptID": "P1782656060858_727",
      "OptionText": "Poached",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782656106316_854",
      "PromptID": "P1782656060858_727",
      "OptionText": "Scrambled",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 3,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782656250339_531",
      "PromptID": "P1782656217930_829",
      "OptionText": "Sausage",
      "Action": "none",
      "Value": "",
      "Price": 1.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": true,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782656264660_278",
      "PromptID": "P1782656217930_829",
      "OptionText": "Bacon",
      "Action": "none",
      "Value": "",
      "Price": 1.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": true,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782657393822_617",
      "PromptID": "P1782656025085_933",
      "OptionText": "None",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 3,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782657403699_977",
      "PromptID": "P1782656060858_727",
      "OptionText": "none",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 4,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782657421373_446",
      "PromptID": "P1782656217930_829",
      "OptionText": "none",
      "Action": "none",
      "Value": "",
      "Price": 0.0,
      "Sort": 3,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782669322015_714",
      "PromptID": "P1782669309730_362",
      "OptionText": "Bacon",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782669337310_443",
      "PromptID": "P1782669309730_362",
      "OptionText": "Sausage",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782669397362_952",
      "PromptID": "P1782669309730_362",
      "OptionText": "Egg",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.7,
      "Sort": 3,
      "Active": false,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782669414566_767",
      "PromptID": "P1782669309730_362",
      "OptionText": "Mushrooms",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.7,
      "Sort": 4,
      "Active": false,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782669438464_561",
      "PromptID": "P1782669309730_362",
      "OptionText": "Tomatoes",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.7,
      "Sort": 5,
      "Active": false,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782669488167_280",
      "PromptID": "P1782656217930_829",
      "OptionText": "Egg",
      "Action": "none",
      "Value": "",
      "Price": 1.0,
      "Sort": 4,
      "Active": true,
      "AllowValue": true,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782669503132_746",
      "PromptID": "P1782656217930_829",
      "OptionText": "Mushrooms",
      "Action": "none",
      "Value": "",
      "Price": 1.0,
      "Sort": 5,
      "Active": true,
      "AllowValue": true,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782669542338_819",
      "PromptID": "P1782656217930_829",
      "OptionText": "tomatoes",
      "Action": "none",
      "Value": "",
      "Price": 1.0,
      "Sort": 6,
      "Active": true,
      "AllowValue": true,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782669594888_756",
      "PromptID": "P1782656217930_829",
      "OptionText": "Black Pudding",
      "Action": "none",
      "Value": "",
      "Price": 1.0,
      "Sort": 7,
      "Active": true,
      "AllowValue": true,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782670259685_226",
      "PromptID": "P1782670248767_972",
      "OptionText": "Ham",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782670264885_914",
      "PromptID": "P1782670248767_972",
      "OptionText": "Cheese",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782670310021_33",
      "PromptID": "P1782670291939_777",
      "OptionText": "bacon Yes",
      "Action": "Modifier",
      "Value": "",
      "Price": 1.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782670675381_793",
      "PromptID": "P1782670649954_117",
      "OptionText": "Sandwich / normal Bread",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782670698722_576",
      "PromptID": "P1782670649954_117",
      "OptionText": "Roll / Bap /Cob",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782670741471_981",
      "PromptID": "P1782670720725_802",
      "OptionText": "White",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782670755613_941",
      "PromptID": "P1782670720725_802",
      "OptionText": "Granary",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782670866545_191",
      "PromptID": "P1782670841986_326",
      "OptionText": "Normal Bread - sandwich",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782670886420_614",
      "PromptID": "P1782670841986_326",
      "OptionText": "Roll",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782670908967_978",
      "PromptID": "P1782670896865_479",
      "OptionText": "White",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782670916881_527",
      "PromptID": "P1782670896865_479",
      "OptionText": "Granary",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671005465_979",
      "PromptID": "P1782670988765_8",
      "OptionText": "Normal sandwich",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671020425_951",
      "PromptID": "P1782670988765_8",
      "OptionText": "Roll / cob",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671060229_296",
      "PromptID": "P1782671039163_411",
      "OptionText": "White",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671115131_347",
      "PromptID": "P1782671103928_679",
      "OptionText": "Sandwich",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671120829_678",
      "PromptID": "P1782671103928_679",
      "OptionText": "Roll",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671151669_628",
      "PromptID": "P1782671137622_875",
      "OptionText": "White",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671158523_391",
      "PromptID": "P1782671137622_875",
      "OptionText": "Granary",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671235662_170",
      "PromptID": "P1782671214961_788",
      "OptionText": "Sandwich",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671248467_535",
      "PromptID": "P1782671214961_788",
      "OptionText": "Roll / cob",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671346504_491",
      "PromptID": "P1782671273652_723",
      "OptionText": "White",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671370935_297",
      "PromptID": "P1782671273652_723",
      "OptionText": "Granary",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671635116_319",
      "PromptID": "P1782671625353_843",
      "OptionText": "White",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671642136_577",
      "PromptID": "P1782671625353_843",
      "OptionText": "Granary",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671742651_752",
      "PromptID": "P1782671731427_496",
      "OptionText": "White",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671770619_518",
      "PromptID": "P1782671731427_496",
      "OptionText": "Granary",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671830845_762",
      "PromptID": "P1782671801202_159",
      "OptionText": "White",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782671837171_697",
      "PromptID": "P1782671801202_159",
      "OptionText": "Granary",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782672813731_667",
      "PromptID": "P1782672804167_232",
      "OptionText": "Scrambled",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782672824415_876",
      "PromptID": "P1782672804167_232",
      "OptionText": "Poached",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782672843284_579",
      "PromptID": "P1782672804167_232",
      "OptionText": "Fried",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 3,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673012852_66",
      "PromptID": "P1782673004962_498",
      "OptionText": "None",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673023400_398",
      "PromptID": "P1782673004962_498",
      "OptionText": "Vanilla",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.5,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673039329_247",
      "PromptID": "P1782673004962_498",
      "OptionText": "Caramel",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.5,
      "Sort": 3,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673104468_989",
      "PromptID": "P1782673004962_498",
      "OptionText": "Hazelnut",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.5,
      "Sort": 4,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673241044_768",
      "PromptID": "P1782673229331_122",
      "OptionText": "Vanilla",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.5,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673253706_168",
      "PromptID": "P1782673229331_122",
      "OptionText": "Caramel",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.5,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673264261_109",
      "PromptID": "P1782673229331_122",
      "OptionText": "Hazelnut",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.5,
      "Sort": 3,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673392809_262",
      "PromptID": "P1782673368316_835",
      "OptionText": "Double",
      "Action": "Modifier",
      "Value": "",
      "Price": 1.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673400121_243",
      "PromptID": "P1782673368316_835",
      "OptionText": "Single",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673451035_766",
      "PromptID": "P1782673424197_513",
      "OptionText": "No",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673549659_258",
      "PromptID": "P1782673521633_691",
      "OptionText": "Cream only",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.25,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673574133_670",
      "PromptID": "P1782673521633_691",
      "OptionText": "Both",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.5,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673584671_201",
      "PromptID": "P1782673521633_691",
      "OptionText": "None",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 3,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673725338_38",
      "PromptID": "P1782673706645_426",
      "OptionText": "Vanilla",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673737060_404",
      "PromptID": "P1782673706645_426",
      "OptionText": "Strawberry",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673746330_525",
      "PromptID": "P1782673706645_426",
      "OptionText": "Banana",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 3,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673757448_469",
      "PromptID": "P1782673706645_426",
      "OptionText": "Chocolate",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 4,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673799850_378",
      "PromptID": "P1782673782787_326",
      "OptionText": "Only Cream",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.25,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673816071_41",
      "PromptID": "P1782673782787_326",
      "OptionText": "Both",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.5,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782673840394_949",
      "PromptID": "P1782673782787_326",
      "OptionText": "None",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 3,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782678994386_352",
      "PromptID": "P1782678982466_39",
      "OptionText": "Yes",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782679008453_556",
      "PromptID": "P1782678982466_39",
      "OptionText": "No",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782730861176_345",
      "PromptID": "P1782669364652_641",
      "OptionText": "Egg",
      "Action": "Modifier",
      "Value": "",
      "Price": 1.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782730879722_383",
      "PromptID": "P1782669364652_641",
      "OptionText": "Tomatoes",
      "Action": "Modifier",
      "Value": "",
      "Price": 1.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782730909723_17",
      "PromptID": "P1782669364652_641",
      "OptionText": "Mushrooms",
      "Action": "Modifier",
      "Value": "",
      "Price": 1.0,
      "Sort": 3,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782731418048_568",
      "PromptID": "P1782671039163_411",
      "OptionText": "Granary",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782731529956_370",
      "PromptID": "P1782670291939_777",
      "OptionText": "No",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782731761473_2",
      "PromptID": "P1782673229331_122",
      "OptionText": "None",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 4,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782732038379_753",
      "PromptID": "P1782732026962_42",
      "OptionText": "White",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782732047420_253",
      "PromptID": "P1782732026962_42",
      "OptionText": "Granary",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782732097449_56",
      "PromptID": "P1782732082198_82",
      "OptionText": "White",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782732104233_76",
      "PromptID": "P1782732082198_82",
      "OptionText": "Granary",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782732178264_642",
      "PromptID": "P1782732169490_761",
      "OptionText": "White",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782732186219_79",
      "PromptID": "P1782732169490_761",
      "OptionText": "Granary",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "Omqzseelbeylh5",
      "PromptID": "Pmqzseelbp0zgy",
      "OptionText": "White",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "Omqzseelb1abmw",
      "PromptID": "Pmqzseelbp0zgy",
      "OptionText": "Granary",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782847529725319",
      "PromptID": "P1782847529725723",
      "OptionText": "Sandwich / normal Bread",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782847529725284",
      "PromptID": "P1782847529725723",
      "OptionText": "Roll / Bap /Cob",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782847529725265",
      "PromptID": "P1782847529725908",
      "OptionText": "White",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 1,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    },
    {
      "OptionID": "O1782847529725592",
      "PromptID": "P1782847529725908",
      "OptionText": "Granary",
      "Action": "Modifier",
      "Value": "",
      "Price": 0.0,
      "Sort": 2,
      "Active": true,
      "AllowValue": false,
      "UpdatedAt": ""
    }
  ],
  "staff": [
    {
      "StaffID": "S0001",
      "StaffName": "Admin",
      "PIN": "0000",
      "Role": "admin",
      "Active": true,
      "CanRefund": true,
      "CanAdmin": true,
      "DiscountAllowed": true,
      "UpdatedAt": "2026-07-04 00:57:01"
    }
  ],
  "settings": {
    "DatabaseVersion": "1.8.8",
    "FrontendVersion": "1.8.8",
    "BackendVersion": "1.8.8",
    "CafeName": "THE NOOK",
    "StaffDiscountPercent": "10",
    "ReceiptPrintingEnabled": "false",
    "PrintCustomerReceipt": "true",
    "PrintTillReceipt": "true",
    "PrintKitchenReceipt": "false",
    "PrinterIP": "",
    "PrinterPort": "9100",
    "TicketPrefix": "",
    "BusinessDateMode": "local"
  },
  "source": "uploaded-test-bed-cleaned"
};
