const fs=require('fs'),assert=require('assert');
const app=fs.readFileSync('js/app.js','utf8');
const foundation=fs.readFileSync('js/foundation.js','utf8');
const release=fs.readFileSync('js/release.js','utf8');
assert(release.includes("appVersion: '3.13.19'"));
assert(release.includes('menuPollIntervalMs: 60000'));
assert(app.includes('Background menu synchronisation never calls render()'));
assert(app.includes("Invalid Kitchen snapshot — keeping existing tickets"));
assert(app.includes('pendingMenuData'));
assert(app.includes('hasConfirmedServerData'));
assert(app.includes('syncErrorState.consecutive404'));
const raw=app.slice(app.indexOf('async function syncMenuData'),app.indexOf('async function syncTicketHistoryData'));
const menuBlock=raw.replace(/\/\/[^\n]*/g,'');
assert(!menuBlock.includes('renderTill()'));
assert(!menuBlock.includes('renderAdmin()'));
assert(!/\brender\(\)/.test(menuBlock));
assert(foundation.includes('AbortController'));
assert(foundation.includes('httpError.status = response.status'));
console.log('3.13.18 blank-screen and 404 stability checks passed');
