const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const app=fs.readFileSync(path.join(root,'js/app.js'),'utf8');
const release=fs.readFileSync(path.join(root,'js/release.js'),'utf8');
assert(release.includes("appVersion: '3.13.20'"));
assert(app.includes('var WAKE_RECOVERY_WATCHDOG_MS = 12000'));
assert(app.includes('var wakeRecoveryGeneration = 0'));
assert(app.includes('async function runWakeConsistencyCheck(generation)'));
assert(app.includes("await api('connectionCheck')"));
assert(app.includes("state.activeTab === 'Kitchen'"));
assert(app.includes('await syncKitchenQueue({ silent: true, foregroundWake: true })'));
assert(app.includes('await syncTillLiveData()'));
assert(app.includes('await syncMenuData()'));
assert(app.includes('Promise.race([runWakeConsistencyCheck(generation), wakeWatchdogPromise(generation)])'));
assert(app.includes("window.addEventListener('focus'"));
const vis=app.slice(app.indexOf("document.addEventListener('visibilitychange'"), app.indexOf("window.addEventListener('pageshow'"));
assert(!vis.includes('syncKitchenQueue'), 'visibility handler must not launch duplicate kitchen request');
const wake=app.slice(app.indexOf('async function resumeBackgroundSyncAfterWake()'),app.indexOf('function scheduleWakeResume('));
assert(!wake.includes('render();'));
assert(!wake.includes('renderTill()'));
assert(!wake.includes('bootstrap('));
assert(wake.includes('wakeSyncInProgress = false'));
console.log('browser resume recovery 3.13.18 tests passed');
