const fs = require('fs');
const assert = require('assert');
const app = fs.readFileSync('js/app.js', 'utf8');
const release = fs.readFileSync('js/release.js', 'utf8');
const backend = fs.readFileSync('google/Code.gs', 'utf8');
const build = JSON.parse(fs.readFileSync('build-info.json', 'utf8'));
assert(app.includes("Saving this prompt option to Google Sheets."), 'prompt option busy message missing');
assert(app.includes("busyMessage: 'Saving this category to Google Sheets.'"), 'category busy message missing');
assert(app.includes("Saving this refund to Google Sheets."), 'refund busy message missing');
assert(app.includes("Confirming the deployed script and version before loading the database."), 'script URL connection-check busy message missing');
assert(app.includes("Loading menu and operational data. A Google Apps Script cold start may take up to 45 seconds."), 'full database load busy message missing');
assert(app.includes("if (action === 'save-settings') saveScriptUrlSetting();"), 'settings save is not routed through async busy handler');
assert(app.includes('openRefundModal(ticketId);'), 'failed refund does not restore refund modal');
assert(release.includes(`appVersion: '${build.release}'`), 'frontend version not synchronized');
assert(backend.includes(`var NOOK_VERSION = '${build.backendVersion}';`), 'backend version not synchronized');
console.log('busy-status-1_3_2.test.js passed');
