const fs = require('fs');
const assert = require('assert');
const release = fs.readFileSync('js/release.js', 'utf8');
const config = fs.readFileSync('js/config.js', 'utf8');
const app = fs.readFileSync('js/app.js', 'utf8');
const backend = fs.readFileSync('google/Code.gs', 'utf8');
const html = fs.readFileSync('index.html', 'utf8');
const seed = fs.readFileSync('js/seed-data.js', 'utf8');
assert(release.includes("frontendVersion: '1.1.5'"));
assert(release.includes("backendVersion: '1.1.5'"));
assert(config.includes('RELEASE.frontendVersion'));
assert(html.includes('js/release.js?v=1.1.5'));
assert(app.includes('function startSyncCoordinator()'));
assert(app.includes('setInterval(runSyncCoordinator, SYNC_TICK_INTERVAL_MS)'));
assert(!app.includes('startMenuPolling'));
assert(!app.includes('startKitchenPolling'));
assert(backend.includes("var NOOK_VERSION = '1.1.5'"));
assert(seed.includes('"FrontendVersion": "1.1.5"'));
console.log('Consolidated release tests passed');
