const fs = require('fs');
const assert = require('assert');
const release = fs.readFileSync('js/release.js', 'utf8');
const config = fs.readFileSync('js/config.js', 'utf8');
const app = fs.readFileSync('js/app.js', 'utf8');
const backend = fs.readFileSync('google/Code.gs', 'utf8');
const html = fs.readFileSync('index.html', 'utf8');
const seed = fs.readFileSync('js/seed-data.js', 'utf8');
assert(release.includes("appVersion: '3.8.6'"));
assert(release.includes("appVersion: '3.8.6'"));
assert(config.includes('RELEASE.appVersion'));
assert(html.includes('js/release.js?v=3.8.6'));
assert(app.includes('function startSyncCoordinator()'));
assert(app.includes('Operations.createPollCoordinator'));
assert(!app.includes('startMenuPolling'));
assert(!app.includes('startKitchenPolling'));
assert(backend.includes("var NOOK_VERSION = '3.8.6'"));
assert(seed.includes('"FrontendVersion": "3.8.6"'));
console.log('Consolidated release tests passed');
