const fs=require('fs'), assert=require('assert');
const app=fs.readFileSync('js/app.js','utf8');
const backend=fs.readFileSync('google/Code.gs','utf8');
const release=fs.readFileSync('js/release.js','utf8');
assert(release.includes("appVersion: '3.13.20'"));
assert(app.includes("LOCAL_TICKET_LIMIT = 500"));
assert(app.includes("consecutiveCoreSyncFailures >= 4"));
assert(app.includes("delays = [5000, 10000, 20000, 30000, 60000]"));
assert(app.includes("menuRetryTimer"));
assert(app.includes("if (menuPollInFlight || !backgroundSyncAllowed()) return"));
assert(app.includes("Device Local Tickets"));
assert(app.includes("storeLocalPaidTicket"));
assert(app.includes("syncLocalTickets"));
assert(app.includes("syncStatus: 'PENDING_SYNC'"));
assert(app.includes("data-action=\"toggle-local-ticket-complete\""));
assert(app.includes("window.addEventListener('offline'"));
assert(app.includes("window.addEventListener('online'"));
assert(backend.includes('ticketBundleByClientRequestId_'));
assert(backend.includes("if (existing) return existing"));
assert(!app.includes("setLocalMode(true);\n  bootstrap()"));
console.log('3.13.18 device local mode and retry safety checks passed');
