const fs = require('fs');
const vm = require('vm');
const assert = require('assert');
const release = fs.readFileSync('js/release.js','utf8');
const config = fs.readFileSync('js/config.js','utf8');
const foundation = fs.readFileSync('js/foundation.js','utf8');
const app = fs.readFileSync('js/app.js','utf8');
const backend = fs.readFileSync('google/Code.gs','utf8');
assert(release.includes("appVersion: '3.13.19'"));
assert(release.includes("acceptedBackendVersions: Object.freeze(['3.13.18', '3.13.17', '3.13.16'])"));
assert(release.includes("acceptedDatabaseVersions: Object.freeze(['1.0.6'])"));
assert(config.includes('acceptedBackendVersions'));
assert(app.includes('function releaseCompatibility'));
assert(app.includes("acceptedBackends.indexOf(backend) >= 0"));
assert(backend.includes("var NOOK_VERSION = '3.13.18';"));
const context={window:{},globalThis:{},console}; vm.createContext(context); vm.runInContext(foundation,context);
const check=context.window.NookFoundation.assertReleaseCompatibility;
const rel={frontendVersion:'3.13.19',acceptedBackendVersions:['3.13.18','3.13.17','3.13.16'],acceptedDatabaseVersions:['1.0.6']};
assert.strictEqual(check(rel,{BackendVersion:'3.13.18',DatabaseVersion:'1.0.6'}).ok,true);
assert.strictEqual(check(rel,{BackendVersion:'3.13.17',DatabaseVersion:'1.0.6'}).ok,true);
assert.strictEqual(check(rel,{BackendVersion:'3.13.16',DatabaseVersion:'1.0.6'}).ok,true);
assert.strictEqual(check(rel,{BackendVersion:'3.13.6',DatabaseVersion:'1.0.6'}).ok,false);
assert.strictEqual(check(rel,{BackendVersion:'3.13.5',DatabaseVersion:'1.0.6'}).ok,false);
assert.strictEqual(check(rel,{BackendVersion:'3.13.18',DatabaseVersion:'1.0.7'}).ok,false);
console.log('3.13.18 explicit compatibility checks passed');
