const fs = require('fs');
const assert = require('assert');
const app = fs.readFileSync('js/app.js','utf8');
const css = fs.readFileSync('css/app.css','utf8');
const index = fs.readFileSync('index.html','utf8');
assert(index.includes('id="uiVersion">3.13.22<'));
assert(!css.includes('@media (max-width: 1180px) {\n  #appShell') || css.includes('.brand-version { display:block; font-size:14px'));
assert(css.includes('.nav-drawer {\n  position:absolute;'));
assert(css.includes('.nav-drawer { position:fixed; top:62px'));
assert(app.includes("state.status.message = 'System OK';"));
assert(app.includes("window.addEventListener('resize'"));
assert(app.includes('recoverStatusIfHealthy();\n      renderStatus();'));
console.log('3.13.18 header/status recovery checks passed');
