const fs = require('fs');
const assert = require('assert');
const app = fs.readFileSync('js/app.js','utf8');
const css = fs.readFileSync('css/app.css','utf8');
const release = fs.readFileSync('js/release.js','utf8');
const backend = fs.readFileSync('google/Code.gs','utf8');
assert(app.includes("item.CategoryName || categoryName(item.CategoryID) || 'Uncategorised'"), 'Kitchen items must resolve their category name');
assert(app.includes('kitchen-item-category'), 'Kitchen ticket lines must render the category');
assert(css.includes('.kitchen-item-category'), 'Kitchen category must use a visible POS style');
assert(release.includes("appVersion: '3.13.20'"), 'Frontend version must be 3.13.18');
assert(release.includes("appVersion: '3.13.20'"), 'Backend version must be 3.13.18');
assert(backend.includes("var NOOK_VERSION = '3.13.18'"), 'Compatible backend must remain 3.13.18');
console.log('kitchen category 3.13.18 checks passed');
