const fs=require('fs');
const assert=require('assert');
const app=fs.readFileSync('js/app.js','utf8');
const code=fs.readFileSync('google/Code.gs','utf8');
assert(code.includes("var NOOK_VERSION = '3.13.18'"));
assert(code.includes("if (action === 'itemConfigurationSnapshot')"));
assert(code.includes('function itemConfigurationSnapshotResponse_'));
assert(code.includes("rowsToObjects_('Prompts')"));
assert(code.includes("rowsToObjects_('PromptOptions')"));
const saveStart=code.indexOf('function saveItemConfiguration_');
const saveEnd=code.indexOf('function savePromptOptionsBatch_', saveStart);
const saveBlock=code.slice(saveStart,saveEnd);
assert(saveBlock.includes('itemConfigurationSnapshotResponse_(itemId).configuration'));
assert(app.includes("api('itemConfigurationSnapshot', { itemId: id })"));
assert(app.includes('configurationMismatchMessage(config, confirmed)'));
assert(app.includes('replaceItemConfigurationInState(id, confirmed)'));
assert(!app.slice(app.indexOf('async function saveItemConfiguration()'), app.indexOf('async function guardAdminNavigation()')).includes("api('bootstrap')"));
assert(app.includes('data-option-field="Active"'));
assert(app.includes('Modifier / add-on'));
assert(app.includes('Selection only'));
console.log('3.13.18 menu configuration round-trip checks passed');
