const fs = require('fs');
const assert = require('assert');
const app = fs.readFileSync('js/app.js', 'utf8');
const release = fs.readFileSync('js/release.js', 'utf8');
assert(release.includes("appVersion: '3.13.19'"));
assert(app.includes('async function bootstrap(options)'));
assert(app.includes('var preserveData = options.preserveData === true || (options.resetData !== true && hasConfirmedServerData)'));
assert(app.includes("bootstrap({ preserveData: true })"));
assert(app.includes("data-action=\"refresh-kitchen\""));
assert(app.includes('async function refreshKitchenOnly()'));
assert(app.includes("name: 'ticket-history'"));
assert(app.includes('async function syncTicketHistoryData()'));
console.log('3.13.18 refresh stability and cross-device ticket sync checks passed.');
