const fs = require('fs');
const assert = require('assert');
const app = fs.readFileSync('js/app.js','utf8');
const backend = fs.readFileSync('google/Code.gs','utf8');
const config = fs.readFileSync('js/config.js','utf8');
const release = fs.readFileSync('js/release.js','utf8');
const html = fs.readFileSync('index.html','utf8');
assert(release.includes("appVersion: '3.8.4'"));
assert(html.includes('id="uiVersion"'));
assert(app.includes("uiVersionEl.textContent = CONFIG.frontendVersion"));
assert(app.includes("data-action=\"export-reports\""));
assert(app.includes("data-action=\"clear-reports\""));
assert(backend.includes("action === 'clearReports'"));
assert(backend.includes("request.passcode || '').trim() !== '2702'"));
assert(app.includes('Passcode hint: <strong>Wiesheu</strong>'));
assert(app.includes('class="pos-keypad"'));
assert(app.includes("api('clearReports', { passcode: passcode })"));
assert(backend.includes("setMeta_('NextTicketNumber', '0')"));
assert(backend.includes("action === 'menuSnapshot'"));
assert(release.includes('menuPollIntervalMs: 5000'));
assert(config.includes('RELEASE.appVersion'));
console.log('Version, reports and menu sync tests passed');
