const fs=require('fs'),assert=require('assert');
const app=fs.readFileSync('js/app.js','utf8');
const css=fs.readFileSync('css/app.css','utf8');
const index=fs.readFileSync('index.html','utf8');
assert(index.includes('id="uiVersion">3.13.22<'));
assert(app.includes("data-action=\"open-payment-method\""));
assert(app.includes('function openPaymentMethodModal()'));
assert(app.includes('data-method="Cash"'));
assert(app.includes('data-method="Card"'));
assert(!app.includes('data-method="Mixed"'));
assert(app.includes('function cashKeypadStatus(digits)'));
assert(app.includes("label: 'STILL TO PAY'"));
assert(app.includes("label: 'CHANGE'"));
assert(app.includes('data-modal-action="complete-cash-sale"'));
assert(app.includes("await commitPayment('Cash')"));
assert(app.includes('id="completeCashSale"'));
assert(app.includes("complete.disabled = !status.canComplete"));
assert(css.includes('.ticket-primary-actions'));
assert(css.includes('.cash-change-panel strong { font-size:48px'));
assert(css.includes('.receipt-change-due strong { font-size:42px'));
console.log('3.13.18 streamlined payment flow checks passed');
