const fs = require('fs');
const assert = require('assert');
const app = fs.readFileSync('js/app.js','utf8');
const css = fs.readFileSync('css/app.css','utf8');
const backend = fs.readFileSync('google/Code.gs','utf8');
const coordinator = fs.readFileSync('js/server-coordinator.js','utf8');
const foundation = fs.readFileSync('js/foundation.js','utf8');
const release = fs.readFileSync('js/release.js','utf8');
assert(release.includes("appVersion: '3.13.20'"));
assert(app.includes('Edit menu layout'));
assert(app.includes('tillLayoutEditMode'));
assert(app.includes('data-layout-type="category"'));
assert(app.includes('data-layout-type="item"'));
assert(app.includes("saveServerEntity('saveCategory'"));
assert(app.includes("saveServerEntity('saveItem'"));
assert(app.includes('Saving Till layout — Please wait'));
assert(app.includes('themedConfirm({ title: \'Discard Till layout changes?\''));
assert(!app.includes("window.confirm('Discard the Till layout changes?')"));
assert(css.includes('.till-layout-editor-bar'));
assert(!backend.includes("action === 'saveTillLayoutArrangement'"));
assert(!backend.includes('function saveTillLayoutArrangement_'));
assert(!coordinator.includes("'saveTillLayoutArrangement'"));
assert(!foundation.includes("'saveTillLayoutArrangement'"));
assert(app.includes('Saving 0 of '));
console.log('Till layout editor 3.13.18 tests passed.');
