const fs = require('fs');
const assert = require('assert');
const app = fs.readFileSync('js/app.js', 'utf8');
const css = fs.readFileSync('css/app.css', 'utf8');
const build = JSON.parse(fs.readFileSync('build-info.json', 'utf8'));
assert.strictEqual(build.release, '3.13.22');
assert(app.includes('collectAdminItemConfiguration'), 'working configuration collector missing');
assert(app.includes('captureAdminItemBaseline'), 'authoritative configuration snapshot missing');
assert(app.includes('adminItemConfigurationDirty'), 'normalised dirty comparison missing');
assert(app.includes('data-action="save-item-configuration"'), 'single Save Configuration control missing');
assert(app.includes('guardAdminNavigation'), 'shared unsaved navigation guard missing');
assert(app.includes("data-unsaved-choice=\"save\""), 'save choice missing');
assert(app.includes("data-unsaved-choice=\"discard\""), 'discard choice missing');
assert(app.includes("data-unsaved-choice=\"stay\""), 'stay choice missing');
assert(app.includes("window.addEventListener('beforeunload'"), 'browser close/refresh guard missing');
assert(css.includes('.item-configuration-savebar'), 'sticky configuration save bar styles missing');
assert(!app.includes('data-action="save-prompt" data-admin-save="prompt"'), 'scattered prompt save button remains');
assert(!app.includes('data-action="save-prompt-options"'), 'scattered option save button remains');
console.log('3.13.18 unified item configuration checks passed.');
