const fs=require('fs'),assert=require('assert');
const build=JSON.parse(fs.readFileSync('build-info.json','utf8'));
const release=fs.readFileSync('js/release.js','utf8');
const config=fs.readFileSync('js/config.js','utf8');
const app=fs.readFileSync('js/app.js','utf8');
const backend=fs.readFileSync('google/Code.gs','utf8');
assert.strictEqual(build.release,'3.13.22');
assert(release.includes("appVersion: '3.13.22'"));
assert(!release.includes('frontendVersion:'));
assert(release.includes("acceptedBackendVersions: Object.freeze(['3.13.18', '3.13.17', '3.13.16'])"));
assert(config.includes('frontendVersion: RELEASE.appVersion'));
assert(config.includes('acceptedBackendVersions'));
assert(app.includes('versionDiagnosticsHtml'));
assert(app.includes('Browser application'));
assert(app.includes('Apps Script backend'));
assert(backend.includes("var NOOK_VERSION = '3.13.18';"));
console.log('3.13.18 single-source version authority tests passed');
