const fs = require('fs');
const assert = require('assert');
const build = JSON.parse(fs.readFileSync('build-info.json', 'utf8'));
const release = fs.readFileSync('js/release.js', 'utf8');
const backend = fs.readFileSync('google/Code.gs', 'utf8');
const html = fs.readFileSync('index.html', 'utf8');
const seed = fs.readFileSync('js/seed-data.js', 'utf8');
assert(release.includes(`appVersion: '${build.release}'`));
assert(!release.includes('frontendVersion:'), 'release.js must expose one application version source');
assert(!release.includes('backendVersion:'), 'release.js must expose one application version source');
assert(release.includes(`databaseVersion: '${build.databaseVersion}'`));
assert(backend.includes(`var NOOK_VERSION = '${build.backendVersion}';`));
assert(backend.includes(`var NOOK_DATABASE_VERSION = '${build.databaseVersion}';`));
assert(seed.includes(`"FrontendVersion": "${build.frontendVersion}"`));
assert(seed.includes(`"BackendVersion": "${build.backendVersion}"`));
assert(html.includes(`js/release.js?v=${build.release}`));
assert(html.includes(`js/foundation.js?v=${build.release}`));
assert(html.includes(`id="uiVersion">${build.release}<`));
assert(html.includes(`js/app.js?v=${build.release}`));
console.log(`Release ${build.release} manifest verified.`);
